GET {{url}}/clients
Accept: application/json
Authorization: Bearer {{token}}

###
GET {{url}}/clients/1
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{url}}/clients
Accept: application/json
Content-Type:application/json
Authorization: Bearer {{token}}

{
  "name": "miguel",
  "lastName": "morales",
  "secondLastName": "reyes",
  "email": "cacahuate11@gmail.com",
  "password": "admin12311"
}

###
PATCH {{url}}/clients/1
Accept: application/json
Content-Type:application/json

{
  "id": 1,
  "name": "lololloplolo"
}

###

DELETE {{url}}/clients/2
Accept: application/json

###
